import { getSession } from "next-auth/client";
import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import { db } from "../firebase";

export default function Home({ session, posts }) {
  if (!session) {
    return <Login />;
  }
  return (
    <div>
      <Head>
        <title>Facebook clone</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="shadow-md">
        <Header />
      </div>
      <main className="flex items-stretch justify-between">
        {/* sidebar */}
        <Sidebar />
        {/* feed */}
        <Feed posts={posts} />
        {/* widgets */}
        <Widgets />
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  // console.log(context);
  // prefetching the posts on the server
  const posts = await db
    .collection("fc_posts")
    .orderBy("timestamp", "desc")
    .get();
  // prepare for component hydration
  const preparedPost = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }));
  return {
    props: {
      session,
      posts: preparedPost,
    },
  };
};
